# Example ScaledObject configuration for rabbitmq-burst-scaler
#
# This ScaledObject will:
# - Scale my-service to 5 replicas when a message arrives on "events" exchange with "jobs.created" routing key
# - Keep 5 replicas for 2 minutes after the last message
# - Scale back to 0 replicas after 2 minutes of no messages
#
# NOTE: RabbitMQ connection settings (host, port, username, password, vhost) are configured
# via environment variables on the burst-scaler deployment, NOT in ScaledObject metadata.
# See the README for deployment configuration.
#
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-service-burst
  namespace: default
spec:
  scaleTargetRef:
    name: my-service                      # Name of the Deployment to scale
  pollingInterval: 5                      # How often KEDA checks the scaler (seconds)
  cooldownPeriod: 30                      # Time before scaling to 0 after metrics drop
  minReplicaCount: 0                      # Minimum replicas (can be 0 for scale-to-zero)
  maxReplicaCount: 10                     # Maximum replicas
  triggers:
  - type: external-push
    metadata:
      scalerAddress: "rabbitmq-burst-scaler.keda-system:9090"  # Address of the burst scaler
      # Source configuration
      exchange: "events"                  # Exchange to bind to
      routingKey: "jobs.created"          # Routing key to listen for
      # Burst configuration
      burstReplicas: "5"                  # Scale to this many replicas
      burstDuration: "2m"                 # Keep replicas for this duration (e.g., "30s", "2m", "1h")
